# Generated by Django 5.0.6 on 2024-07-09 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 7, 9, 20, 55, 59, 572260, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
